server:
  port: 8002
spring:
  application:
    name: config-client
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    username: admin
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
